SHELL=/bin/bash
summary/all.tex: gen
	echo '\summarySection{Loaded Graphs}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{Goal}}{\summaryGraphFile{out/001_g_0_10300000}{\texttt{out/001\_g\_0\_10300000}}}{\summaryGraphFile{out/003_g_0_11310100}{\texttt{out/003\_g\_0\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{Start}}{\summaryGraphFile{out/005_g_1_10300000}{\texttt{out/005\_g\_1\_10300000}}}{\summaryGraphFile{out/007_g_1_11310100}{\texttt{out/007\_g\_1\_11310100}}}' >> summary/all.tex
	echo '\summarySection{Loaded Rules}' >> summary/all.tex
	echo '\summaryRule{Mark for conversion}{\summaryRuleSpan{out/009_r_0_10300000}{out/009\_r\_0\_10300000}}{\summaryRuleSpan{out/011_r_0_11300100}{out/011\_r\_0\_11300100}}{}{out/012_r_0_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Remove R Nodes}{\summaryRuleSpan{out/014_r_1_10300000}{out/014\_r\_1\_10300000}}{\summaryRuleSpan{out/016_r_1_11300100}{out/016\_r\_1\_11300100}}{}{out/017_r_1_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Reattach External Edges}{\summaryRuleSpan{out/019_r_2_10300000}{out/019\_r\_2\_10300000}}{\summaryRuleSpan{out/021_r_2_11300100}{out/021\_r\_2\_11300100}}{}{out/022_r_2_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Remove attached edge}{\summaryRuleSpan{out/024_r_3_10300000}{out/024\_r\_3\_10300000}}{\summaryRuleSpan{out/026_r_3_11300100}{out/026\_r\_3\_11300100}}{}{out/027_r_3_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Remove Inter R-Node Edges}{\summaryRuleSpan{out/029_r_4_10300000}{out/029\_r\_4\_10300000}}{\summaryRuleSpan{out/031_r_4_11300100}{out/031\_r\_4\_11300100}}{}{out/032_r_4_constraints.tex}' >> summary/all.tex
	echo '\summaryDGHyper{\texttt{dg\_0}}{out/034_dg_0_10100}{\texttt{out/034\_dg\_0\_10100}}' >> summary/all.tex
	echo '\summarySection{Product Graphs}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,0\}}}{\summaryGraphFile{out/036_g_2_10300000}{\texttt{out/036\_g\_2\_10300000}}}{\summaryGraphFile{out/038_g_2_11310100}{\texttt{out/038\_g\_2\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,1\}}}{\summaryGraphFile{out/040_g_20_10300000}{\texttt{out/040\_g\_20\_10300000}}}{\summaryGraphFile{out/042_g_20_11310100}{\texttt{out/042\_g\_20\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,2\}}}{\summaryGraphFile{out/044_g_22_10300000}{\texttt{out/044\_g\_22\_10300000}}}{\summaryGraphFile{out/046_g_22_11310100}{\texttt{out/046\_g\_22\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,3\}}}{\summaryGraphFile{out/048_g_25_10300000}{\texttt{out/048\_g\_25\_10300000}}}{\summaryGraphFile{out/050_g_25_11310100}{\texttt{out/050\_g\_25\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,4\}}}{\summaryGraphFile{out/052_g_27_10300000}{\texttt{out/052\_g\_27\_10300000}}}{\summaryGraphFile{out/054_g_27_11310100}{\texttt{out/054\_g\_27\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,5\}}}{\summaryGraphFile{out/056_g_29_10300000}{\texttt{out/056\_g\_29\_10300000}}}{\summaryGraphFile{out/058_g_29_11310100}{\texttt{out/058\_g\_29\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,6\}}}{\summaryGraphFile{out/060_g_34_10300000}{\texttt{out/060\_g\_34\_10300000}}}{\summaryGraphFile{out/062_g_34_11310100}{\texttt{out/062\_g\_34\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,7\}}}{\summaryGraphFile{out/064_g_35_10300000}{\texttt{out/064\_g\_35\_10300000}}}{\summaryGraphFile{out/066_g_35_11310100}{\texttt{out/066\_g\_35\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,8\}}}{\summaryGraphFile{out/068_g_36_10300000}{\texttt{out/068\_g\_36\_10300000}}}{\summaryGraphFile{out/070_g_36_11310100}{\texttt{out/070\_g\_36\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,9\}}}{\summaryGraphFile{out/072_g_40_10300000}{\texttt{out/072\_g\_40\_10300000}}}{\summaryGraphFile{out/074_g_40_11310100}{\texttt{out/074\_g\_40\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,10\}}}{\summaryGraphFile{out/076_g_44_10300000}{\texttt{out/076\_g\_44\_10300000}}}{\summaryGraphFile{out/078_g_44_11310100}{\texttt{out/078\_g\_44\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,11\}}}{\summaryGraphFile{out/080_g_47_10300000}{\texttt{out/080\_g\_47\_10300000}}}{\summaryGraphFile{out/082_g_47_11310100}{\texttt{out/082\_g\_47\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,12\}}}{\summaryGraphFile{out/084_g_50_10300000}{\texttt{out/084\_g\_50\_10300000}}}{\summaryGraphFile{out/086_g_50_11310100}{\texttt{out/086\_g\_50\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,13\}}}{\summaryGraphFile{out/088_g_52_10300000}{\texttt{out/088\_g\_52\_10300000}}}{\summaryGraphFile{out/090_g_52_11310100}{\texttt{out/090\_g\_52\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,14\}}}{\summaryGraphFile{out/092_g_58_10300000}{\texttt{out/092\_g\_58\_10300000}}}{\summaryGraphFile{out/094_g_58_11310100}{\texttt{out/094\_g\_58\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,15\}}}{\summaryGraphFile{out/096_g_70_10300000}{\texttt{out/096\_g\_70\_10300000}}}{\summaryGraphFile{out/098_g_70_11310100}{\texttt{out/098\_g\_70\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,16\}}}{\summaryGraphFile{out/100_g_72_10300000}{\texttt{out/100\_g\_72\_10300000}}}{\summaryGraphFile{out/102_g_72_11310100}{\texttt{out/102\_g\_72\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,17\}}}{\summaryGraphFile{out/104_g_75_10300000}{\texttt{out/104\_g\_75\_10300000}}}{\summaryGraphFile{out/106_g_75_11310100}{\texttt{out/106\_g\_75\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,18\}}}{\summaryGraphFile{out/108_g_76_10300000}{\texttt{out/108\_g\_76\_10300000}}}{\summaryGraphFile{out/110_g_76_11310100}{\texttt{out/110\_g\_76\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,19\}}}{\summaryGraphFile{out/112_g_78_10300000}{\texttt{out/112\_g\_78\_10300000}}}{\summaryGraphFile{out/114_g_78_11310100}{\texttt{out/114\_g\_78\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,20\}}}{\summaryGraphFile{out/116_g_82_10300000}{\texttt{out/116\_g\_82\_10300000}}}{\summaryGraphFile{out/118_g_82_11310100}{\texttt{out/118\_g\_82\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,21\}}}{\summaryGraphFile{out/120_g_83_10300000}{\texttt{out/120\_g\_83\_10300000}}}{\summaryGraphFile{out/122_g_83_11310100}{\texttt{out/122\_g\_83\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,22\}}}{\summaryGraphFile{out/124_g_86_10300000}{\texttt{out/124\_g\_86\_10300000}}}{\summaryGraphFile{out/126_g_86_11310100}{\texttt{out/126\_g\_86\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,23\}}}{\summaryGraphFile{out/128_g_88_10300000}{\texttt{out/128\_g\_88\_10300000}}}{\summaryGraphFile{out/130_g_88_11310100}{\texttt{out/130\_g\_88\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,24\}}}{\summaryGraphFile{out/132_g_94_10300000}{\texttt{out/132\_g\_94\_10300000}}}{\summaryGraphFile{out/134_g_94_11310100}{\texttt{out/134\_g\_94\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,25\}}}{\summaryGraphFile{out/136_g_100_10300000}{\texttt{out/136\_g\_100\_10300000}}}{\summaryGraphFile{out/138_g_100_11310100}{\texttt{out/138\_g\_100\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,26\}}}{\summaryGraphFile{out/140_g_102_10300000}{\texttt{out/140\_g\_102\_10300000}}}{\summaryGraphFile{out/142_g_102_11310100}{\texttt{out/142\_g\_102\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,27\}}}{\summaryGraphFile{out/144_g_105_10300000}{\texttt{out/144\_g\_105\_10300000}}}{\summaryGraphFile{out/146_g_105_11310100}{\texttt{out/146\_g\_105\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,28\}}}{\summaryGraphFile{out/148_g_107_10300000}{\texttt{out/148\_g\_107\_10300000}}}{\summaryGraphFile{out/150_g_107_11310100}{\texttt{out/150\_g\_107\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,29\}}}{\summaryGraphFile{out/152_g_108_10300000}{\texttt{out/152\_g\_108\_10300000}}}{\summaryGraphFile{out/154_g_108_11310100}{\texttt{out/154\_g\_108\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,30\}}}{\summaryGraphFile{out/156_g_114_10300000}{\texttt{out/156\_g\_114\_10300000}}}{\summaryGraphFile{out/158_g_114_11310100}{\texttt{out/158\_g\_114\_11310100}}}' >> summary/all.tex
	echo '\summarySection{Contracted Move Space}' >> summary/all.tex
	echo '\summaryDGHyper{\texttt{dg\_1}}{out/160_dg_1_10100}{\texttt{out/160\_dg\_1\_10100}}' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 0}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/162_f_0_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_0, 0}}{out/169_dg_1_11100_f_0_0_filt}{\texttt{out/169\_dg\_1\_11100\_f\_0\_0\_filt}}' >> summary/all.tex
summary.pdf: summary/all.tex
	mod_post --mode compileSummary
include summary/MakefileImpl
include summary/MakefileDep
include summary/MakefileAllTarget
include summary/MakefileClean
